-- MySQL Script generated by MySQL Workbench
-- Mon Apr 20 01:00:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema platz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema platz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `platz` DEFAULT CHARACTER SET utf8 ;
USE `platz` ;

-- -----------------------------------------------------
-- Table `platz`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `platz`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `platz`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `platz`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `platz`.`produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `platz`.`produits` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `poids` VARCHAR(20) NULL,
  `image` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `categories_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produits_categories_idx` (`categories_id` ASC) VISIBLE,
  INDEX `fk_produits_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_produits_categories`
    FOREIGN KEY (`categories_id`)
    REFERENCES `platz`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produits_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `platz`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `platz`.`commentaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `platz`.`commentaires` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `texte` TEXT NOT NULL,
  `users_id` INT UNSIGNED NOT NULL,
  `produits_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_commentaires_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_commentaires_produits1_idx` (`produits_id` ASC) VISIBLE,
  CONSTRAINT `fk_commentaires_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `platz`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commentaires_produits1`
    FOREIGN KEY (`produits_id`)
    REFERENCES `platz`.`produits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `platz`.`pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `platz`.`pages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `slug` VARCHAR(100) NOT NULL,
  `titre` VARCHAR(100) NULL,
  `texte` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
